# fly.toml app configuration file generated for simwrapper-runners on 2026-08-21T19:52:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simwrapper-runners'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[[vm]]
  memory = '16gb'
  cpus = 8
  memory_mb = 16384
