/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_eventstreamer_free(a: number, b: number): void;
export function eventstreamer_new(): number;
export function zlibVersion(): number;
export function inflateInit2_(a: number, b: number, c: number, d: number): number;
export function eventstreamer_process(a: number, b: number, c: number): Array;
export function inflate(a: number, b: number): number;
export function inflateEnd(a: number): number;
export function crc32(a: number, b: number, c: number): number;
export function crc32_combine(a: number, b: number, c: number): number;
export function adler32(a: number, b: number, c: number): number;
export function adler32_combine(a: number, b: number, c: number): number;
export function uncompress(a: number, b: number, c: number, d: number): number;
export function inflateBackInit_(a: number, b: number, c: number, d: number, e: number): number;
export function inflateBack(a: number, b: number, c: number, d: number, e: number): number;
export function inflateBackEnd(a: number): number;
export function inflateCopy(a: number, b: number): number;
export function inflateMark(a: number): number;
export function inflateSync(a: number): number;
export function inflateSyncPoint(a: number): number;
export function inflateInit_(a: number, b: number, c: number): number;
export function inflatePrime(a: number, b: number, c: number): number;
export function inflateReset(a: number): number;
export function inflateReset2(a: number, b: number): number;
export function inflateSetDictionary(a: number, b: number, c: number): number;
export function inflateGetHeader(a: number, b: number): number;
export function inflateUndermine(a: number, b: number): number;
export function inflateResetKeep(a: number): number;
export function inflateCodesUsed(a: number): number;
export function deflate(a: number, b: number): number;
export function deflateSetHeader(a: number, b: number): number;
export function deflateBound(a: number, b: number): number;
export function compress(a: number, b: number, c: number, d: number): number;
export function compress2(a: number, b: number, c: number, d: number, e: number): number;
export function compressBound(a: number): number;
export function deflateEnd(a: number): number;
export function deflateReset(a: number): number;
export function deflateParams(a: number, b: number, c: number): number;
export function deflateSetDictionary(a: number, b: number, c: number): number;
export function deflatePrime(a: number, b: number, c: number): number;
export function deflatePending(a: number, b: number, c: number): number;
export function deflateCopy(a: number, b: number): number;
export function deflateInit_(a: number, b: number, c: number, d: number): number;
export function deflateInit2_(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function deflateTune(a: number, b: number, c: number, d: number, e: number): number;
export function zError(a: number): number;
export const __wbindgen_export_0: WebAssembly.Table;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_start(): void;
